### ISSUE TITLE
Add an APP_IMPORT_ONLY_CHANNELS option ?

### ISSUE THREAD

**Issue by cvergne** [clem/slack-to-wallabag#6]
Hi,

It would be great to have a `APP_IMPORT_ONLY_CHANNELS` option to specify the channels we want to crawl because in my case, I have only 2 / 60 channels for which I want links to go in Wallabag _(and the chan to exclude is going to grow, so the "exclude chans" param is not very convenient)_.

Good job by the way ;)

**Comment by clem** [comment]
Hi @cvergne :)

Yes, it's a great idea. I'll work on it when I can ;)

Thanks :)

**Comment by clem** [comment]
Hi @cvergne,

I made the changes in a Pull Request : #7 

Can you take a look and tell me if it's okay for you ?

Thanks :)

**Comment by cvergne** [comment]
Hey,

Looks good to me (just the description of the option to fix), thanks !
Let me try it tomorrow if you want before merging it :)

**Comment by cvergne** [comment]
@clem It's working well, there is just

**Comment by cvergne** [comment]
Working well, so I close the issue. Thanks for the feature 🙏🏻

**Comment by clem** [comment]
@cvergne You're welcome ;)
